# Copyright (c) 2024 Stephan Hadan <stephan@hadan.de>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Stephan Hadan
site_url: https://stephan.hadan.de/
site_author: Stephan Hadan
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_url: https://github.com/stiebke/stiebke.github.io
repo_name: stiebke/stiebke.github.io

# Copyright
copyright: Copyright &copy; 2024-2025 Stephan Hadan

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono  
  logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  language: de
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.instant.preview
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

# Plugins
plugins:
  - search
  - privacy:
      enabled: !ENV [CI, false]
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            show_bases: false
            show_source: true
            show_labels: false
            show_root_heading: true
  - optimize:
      enabled: !ENV [CI, false]
  - typeset
  - awesome-pages
  - blog: 
      archive: false
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: stiebke/stiebke.github.io
      branch: main
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
            back: resources/templates/covers/back.html.j2
          aggregator:
            enabled: !ENV [MKDOCS_EXPORTER_PDF_AGGREGATOR, false]
            output: documentation.pdf
            covers: front
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - rss:
      enabled: !ENV [CI, false]      
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - macros

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stiebke
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/stiebke
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/stiebke.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://freiburg.social/@stiebke 
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/hadan72
    - icon: fontawesome/brand/gitter
      link: https://matrix.to/#/@stiebke:gitter.im
    - icon: fontawesome/solid/rss
      link: https://stephan.hadan.de/feed_rss_created.xml
      name: Neueste Blogbeiträge

# Extensions    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

# Extra Javascript
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Page tree
nav:
  - Home:
    - Über mich: index.md
    - Changelog: changelog.md
    - Lizenz: license.md
  - Lebenslauf: cv/index.md
  - Projekte: projects/index.md
  - Tech Stack: techstack/index.md
  - Kontakt: contact/index.md
  - Impressum: imprint/index.md
  - Blog:
    - blog/index.md  
        
