# Copyright (c) 2024 Stephan Hadan <stephan@hadan.de>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Stephan Hadan
site_url: https://stephan.hadan.de/
site_author: Stephan Hadan
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_url: https://github.com/stiebke/stiebke.github.io
repo_name: stiebke/stiebke.github.io

# Copyright
copyright: Copyright &copy; 2024 Stephan Hadan

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono  
  logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  language: de
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

# Plugins
plugins:
  - search
  - blog: 
      archive: false
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: stiebke/stiebke.github.io
      branch: main
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
            back: resources/templates/covers/back.html.j2
          aggregator:
            enabled: !ENV [MKDOCS_EXPORTER_PDF_AGGREGATOR, false]
            output: documentation.pdf
            covers: front
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - rss:
      enabled: !ENV [CI, false]      
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stiebke
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/stiebke
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/stiebke.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://freiburg.social/@stiebke 

# Extensions    
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist

# Page tree
nav:
  - Home:
    - Über mich: index.md
    - Über diese Website: about-website.md
  - Lebenslauf: cv/index.md
  - Projekte: projects/index.md
  - Tech Stack: techstack/index.md
  - Kontakt: contact/index.md
  - Impressum: imprint/index.md
  - Blog:
    - blog/index.md  
        